using System.Collections.Generic;

namespace Tweaker.Utilities;

internal static class LocalizationCatalog
{
    // Traducción exacta de frases completas (es -> en)
    public static readonly IReadOnlyDictionary<string, string> SpanishToEnglishExact = new Dictionary<string, string>
    {
        ["Ghost Optimizer - Gaming Tweaker"] = "Ghost Optimizer - Gaming Tweaker",
        ["Acciones Rápidas"] = "Quick Actions",
        ["Crear Punto de Restauración"] = "Create Restore Point",
        ["Abrir Restauración del Sistema"] = "Open System Restore",
        ["REVERTIR TODOS LOS TWEAKS"] = "REVERT ALL TWEAKS",
        ["Categorías Populares:"] = "Popular Categories:",
        ["Sistema & GPU"] = "System & GPU",
        ["Red & Ping"] = "Network & Ping",
        ["Windows Bloatware"] = "Windows Bloatware",
        ["Kernel Latency"] = "Kernel Latency",
        ["Optimización de Input Lag y FPS"] = "Input Lag and FPS Optimization",
        ["Desactivar Aceleración del Mouse"] = "Disable Mouse Acceleration",
        ["No hay tweaks activos. Comienza activando optimizaciones desde las categorías del menú."] = "No active tweaks. Start by enabling optimizations from menu categories.",
        ["Tweaks Activos"] = "Active Tweaks",
        ["Diagnóstico"] = "Diagnostics",
        ["Herramientas"] = "Tools",
        ["Configuración"] = "Settings",
        ["Aplicar"] = "Apply",
        ["Restaurar"] = "Restore",
        ["Activar"] = "Enable",
        ["Desactivar"] = "Disable",
        ["Punto de Restauración"] = "Restore Point",
        ["Permisos Requeridos"] = "Permissions Required",
        ["Error de Inicio"] = "Startup Error",
        ["Error"] = "Error",
        ["Advertencia"] = "Warning",
        ["Éxito"] = "Success",
        ["Idioma"] = "Language",
        ["ON"] = "ON",
        ["OFF"] = "OFF",
        
        // New Profile & History translations
        ["Historial de Cambios"] = "Change History",
        ["Sistema de Perfiles"] = "Profile System",
        ["Mis Perfiles Guardados"] = "My Saved Profiles",
        ["CREAR PERFIL NUEVO"] = "CREATE NEW PROFILE",
        ["Guardar Configuración Actual"] = "Save Current Configuration",
        ["Crea un perfil con todos los tweaks que tienes activos actualmente para poder restaurarlos más tarde."] = "Create a profile with all your currently active tweaks to restore them later.",
        ["Presets del Sistema"] = "System Presets",
        ["Aplica configuraciones recomendadas por Ghost Optimizer según tu perfil de uso."] = "Apply configurations recommended by Ghost Optimizer based on your usage profile.",
        ["CARGAR"] = "LOAD",
        ["ELIMINAR"] = "DELETE",
        ["Control del Registro"] = "Log Control",
        ["Puedes exportar el historial a tu escritorio o vaciar el registro por completo."] = "You can export the history to your desktop or clear the log completely.",
        ["EXPORTAR REGISTRO"] = "EXPORT LOG",
        ["LIMPIAR HISTORIAL"] = "CLEAR HISTORY",
        ["Historial"] = "History",
        ["Perfiles"] = "Profiles",
        ["Casual"] = "Casual",
        ["Competitivo"] = "Competitive",
        ["Extremo"] = "Extreme",
        ["Creado:"] = "Created:",
        ["IMPORTAR PERFIL"] = "IMPORT PROFILE",
        ["EXPORTAR"] = "EXPORT",
        ["Estado:"] = "Status:",
        ["Escritorio"] = "Desktop",
        ["Auto-Detencion"] = "Auto-Stop",
        ["Detecta juegos automaticamente y optimiza el sistema"] = "Detect games automatically and optimize the system",
        ["si"] = "yes",
        ["Sí"] = "Yes",
        ["No"] = "No",
        ["Guía Rápida & Consejos"] = "Quick Guide & Tips",
        ["Navega por las categorías del menú lateral para explorar optimizaciones de Red, Sistema, Limpieza y más."] = "Navigate through the sidebar categories to explore Network, System, Cleanup optimizations and more.",
        ["Activa los tweaks con el interruptor ON (verde) para aplicar configuraciones optimizadas al instante."] = "Enable tweaks with the ON switch (green) to apply optimized settings instantly.",
        ["Desactiva con el interruptor OFF (rojo) si deseas revertir los cambios a los valores por defecto del sistema."] = "Disable with the OFF switch (red) if you want to revert changes to system defaults.",
        ["Reinicia tu sistema después de aplicar optimizaciones críticas para que todos los cambios surtan efecto."] = "Restart your system after applying critical optimizations for all changes to take effect.",
        ["CONSEJO DE RENDIMIENTO"] = "PERFORMANCE TIP",
        ["Crea siempre un Punto de Restauración del Sistema en la tarjeta de 'Acciones Rápidas' antes de realizar cambios importantes."] = "Always create a System Restore Point in the 'Quick Actions' card before making major changes."
    };

    // Reemplazos parciales para textos largos (es -> en)
    public static readonly IReadOnlyDictionary<string, string> SpanishToEnglishPartial = new Dictionary<string, string>
    {
        ["Optimizaciones"] = "Optimizations",
        ["Optimización"] = "Optimization",
        ["Optimizar"] = "Optimize",
        ["Desactivar"] = "Disable",
        ["Activar"] = "Enable",
        ["Restaurar"] = "Restore",
        ["Revertir"] = "Revert",
        ["Sistema"] = "System",
        ["Red"] = "Network",
        ["Servicios"] = "Services",
        ["Servicio"] = "Service",
        ["Telemetría"] = "Telemetry",
        ["Hibernación"] = "Hibernation",
        ["Aceleración"] = "Acceleration",
        ["Teclado"] = "Keyboard",
        ["Efectos Visuales"] = "Visual Effects",
        ["Ahorro de Energía"] = "Power Saving",
        ["Rendimiento"] = "Performance",
        ["Requiere reinicio"] = "Restart required",
        ["Requiere Reinicio"] = "Restart Required",
        ["Completado"] = "Completed",
        ["Aplicado"] = "Applied",
        ["Guardar"] = "Save",
        ["Cerrar"] = "Close",
        ["Inicio"] = "Startup",
        ["Seguridad"] = "Security",
        ["Diagnóstico"] = "Diagnostics",
        ["Navegadores"] = "Browsers",
        ["Navegador"] = "Browser",
        ["velocidad"] = "speed",
        ["lento"] = "slow",
        ["lentos"] = "slow",
        ["latencia"] = "latency",
        ["actualizaciones"] = "updates",
        ["Actualizaciones"] = "Updates",
        ["Buscar"] = "Search",
        ["Aplicación"] = "Application",
        ["Administrador"] = "Administrator",
        ["reinicia"] = "restart",
        ["reiniciar"] = "restart"
    };
}
